[package]
name = "mjai-reviewer3p"
version = "1.5.11-3p"
authors = ["Equim", "hidacow"]
edition = "2021"
repository = "https://github.com/hidacow/mjai-reviewer3p"
license = "Apache-2.0"
description = "🔍🀄️ Review your Tenhou or Mahjong Soul (Jantama) log with mjai-compatible mahjong AIs. (3 player version)"

[dependencies]
convlog = { path = "./convlog" }

anyhow = "1"
serde_json = "1"
tera = "1"
chrono = "0.4"
ureq = "2"
opener = "0.7"
dunce = "1"
humantime-serde = "1"
url = "2"
serde_with = "3"
minify-html = "0.15"
fluent-templates = { version = "0.11.0", features = ["tera"] }
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }

[workspace]
members = [
    ".",
    "convlog",
]

[profile.release]
debug = 1
lto = true
codegen-units = 1
