[package]
name = "convlog"
version = "0.2.0-3p"
authors = ["Equim <sayaka@ekyu.moe>"]
edition = "2021"

[dependencies]
serde_json = "1"
serde_tuple = "0.5"
serde_repr = "0.1"
thiserror = "1"
num_enum = "0.7"
ahash = "0.8"
serde_with = "3"
serde = { version = "1", features = ["derive"] }
